### ISSUE TITLE
关于Grand Challenge上MSD验证集提交问题

### ISSUE THREAD

**Issue by LinxuanHan** [Ziyan-Huang/FLARE22#2]
大佬您好：
我是华中科技大学计算机专业的一名本科生，很抱歉以这种形式联系您。
我正在MSD上提交验证集，但是出现了这样的问题：
evalutils.exceptions.FileLoaderError: Could not load and files in /input/Task01_BrainTumour with <evalutils.io.SimpleITKLoader object at 0x7fedc5ae6cf8>.
可是，我提交的预测标签都是nii.gz的文件，还是出现上述错误，不知道是什么原因。
由于您在提交榜单上有靠前排名，所以想请教您，您提交的文件是如何保存提交的。还望您能够予以指教，不胜感激。

2023年4月5日

**Comment by Ziyan-Huang** [comment]
同学你好，
可以先检查一下你提交的压缩文件是否是这个格式：
![image](https://user-images.githubusercontent.com/81061735/230058475-27d326ff-c2d6-4ed1-854a-94456f2fcdb1.png)
我先猜测你提交的文件里没有 Task01_BrainTumour 这个文件夹。注意名字是否一致。

**Comment by LinxuanHan** [comment]
大佬您好：
是这样的，我只进行了脑肿瘤分割的模型训练和验证集结果输出，我的提交结果是这样的：


按照您的意思，是不是需要十项内容全部放入，才能有效进行呢？


&nbsp;


浑水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ziyan ***@***.***&gt;; 
发送时间: 2023年4月5日(星期三) 晚上6:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ziyan-Huang/FLARE22] 关于Grand Challenge上MSD验证集提交问题 (Issue #2)





 
同学你好，
 可以先检查一下你提交的压缩文件是否是这个格式：
 
 我先猜测你提交的文件里没有 Task01_BrainTumour 这个文件夹。注意名字是否一致。

**Comment by LinxuanHan** [comment]
大佬您好：
是这样的，我只进行了脑肿瘤分割的模型训练和验证集结果输出，我的提交结果是这样的：
![image](https://user-images.githubusercontent.com/48483218/230061258-14104a3f-5f01-4b13-a3e2-fc8acf2995a7.png)
![image](https://user-images.githubusercontent.com/48483218/230061330-76a95c27-895b-4ac9-95e5-094dc2ef6b0c.png)



按照您的意思，是不是需要十项内容全部放入，才能有效进行呢？

**Comment by Ziyan-Huang** [comment]
可以先试一下你的结果，能否用 SimpleITK 顺利读取。
另外 MSD 可能确实是需要十项内容全部放入（我自己是这样提交的），如果只想测试 Task01 的结果，其它的可以先随意预测一些结果一起交了。

**Comment by LinxuanHan** [comment]
大佬您好，文件读入错误的问题解决了，但是奇怪的问题又增加了。
我在代码里生成对应尺寸的label后提交，
![image](https://user-images.githubusercontent.com/48483218/230344536-3f088946-1be8-4496-97b9-101d8160b6d4.png)
出现了，OOM的问题，
![image](https://user-images.githubusercontent.com/48483218/230344656-b7d9407e-8e61-4555-9467-fe6500760050.png)
根据提交规则，已经明确的更改格式为uint8，并且不是全0数组，而且，每个Label的大小都在200KB以内，很难想象这是什么原因，请问您在提交过程中有遇到过相似问题么？
再次感谢您不厌其烦的予以解答。

**Comment by LinxuanHan** [comment]
我也十分仔细的检查过了每个文件夹下文件的个数，也是和其他人提交文件的个数是相同的

**Comment by LinxuanHan** [comment]
啊，不幸地，我刚才提交了一版一摸一样的，竟然成功提交了，我要崩溃了。:(

**Comment by Scw1217** [comment]
同学你好 我在上传测试集的预测结果的时候出现了和你最开始用样的结果  我只上传了Task07_Pancreas 的预测结果 我需要在我上传的文件夹中创建所有任务的文件夹吗
