### ISSUE TITLE
Pseudo label selection

### ISSUE THREAD

**Issue by wt812549723** [Ziyan-Huang/FLARE22#5]
Based on the code provided in [https://github.com/Ziyan-Huang/FLARE22/blob/main/select.ipynb](https://chat.openai.com/c/url), it appears that three rounds of pseudo-labels are generated. However, the instructions imply that only the first round (involving the model trained with labeled data) and the second round (involving the model trained with the first round of pseudo-labels and labeled data) produce pseudo-label results. Therefore, the process for conducting the third round of iterative training remains unclear. Could you please clarify how to proceed with the third round of training in this iterative process?

**Comment by Ziyan-Huang** [comment]
Hello, we have repeated the procedure described in Section 1.6 of the readme **twice**, leading to a total of three iterations of pseudo-labels. This is the reason we refer to the process as **iterative**. We hope this clarification is helpful.

**Comment by wt812549723** [comment]
Thank you for your patient reply.
